<?php
require(VIEWS_PATH . 'includes/header.phtml');
?>

<div class="container">
    <form method="POST" action="<?=HOME;?>/myexpenses/new">
        <div class="form-group">
            <label for="exampleInputEmail1">Valor Gasto</label>
            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Valor gasto..." name="value">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Descrição</label>
            <textarea name="description" id="" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
    </form>
</div>


<?php
require(VIEWS_PATH . 'includes/footer.phtml');
?>