<?php
require(VIEWS_PATH . 'includes/header.phtml');
?>

<div class="container">
    <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nome completo" name="name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email (Campo Obrigatório)</label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Assunto</label>
            <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Assunto" name="subject">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Mensagem</label>
            <textarea name="message" id="" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Enviar Contacto</button>
    </form>
</div>


<?php
require(VIEWS_PATH . 'includes/footer.phtml');
?>