<?php
require(VIEWS_PATH . 'includes/header.phtml');
?>
<div class="container">
    <div class="jumbotron">
        <h1>Gerenciador de Gastos Pessoais</h1>
        <p>Projecto 3 criado no curso PHP Orientado a Objecto.</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </p>
    </div>
    <div class="col-md-12">
    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>